[package]
name = "onlyargs-tutorial-plain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-iter = "0.4.1"
onlyargs = "0.1.2"
